server:
  port: 8085

spring:
  application:
    name: login
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/login_db

      logging:
        level:
          org:
            springframework:
              data:
                mongodb=DEBUG: